### ISSUE TITLE
Parsing snpeff vcf to maff error

### ISSUE THREAD

**Issue by MiguelJulia** [cbare/vcf2maf#1]
Hi,

I am trying to parse a vcf created by snpeff to get a maf file, but I get the following error:

[miguel]$ python /bmm/home/mj308/vcf2maf-master/vcf2maf/vcf2maf.py -v --maf par.realigned.bam.filtered.vcf.snpeff.maf par.realigned.bam.filtered.vcf.snpeff.vcf
processing file: par.realigned.bam.filtered.vcf.snpeff.vcf
Traceback (most recent call last):
  File "/bmm/home/mj308/vcf2maf-master/vcf2maf/vcf2maf.py", line 556, in <module>
    main()
  File "/bmm/home/mj308/vcf2maf-master/vcf2maf/vcf2maf.py", line 543, in main
    n += vcf2maf(vcf_file, maf_file, decrement_end_coordinate=args.decrement_end_coordinate, verbose=args.verbose)
  File "/bmm/home/mj308/vcf2maf-master/vcf2maf/vcf2maf.py", line 182, in vcf2maf
    vcf_reader = vcf.Reader(vcf_file)
  File "/usr/lib/python2.6/site-packages/PyVCF-0.6.8.dev0-py2.6.egg/vcf/parser.py", line 296, in **init**
    self._parse_metainfo()
  File "/usr/lib/python2.6/site-packages/PyVCF-0.6.8.dev0-py2.6.egg/vcf/parser.py", line 322, in _parse_metainfo
    key, val = parser.read_filter(line)
  File "/usr/lib/python2.6/site-packages/PyVCF-0.6.8.dev0-py2.6.egg/vcf/parser.py", line 143, in read_filter
    "One of the FILTER lines is malformed: %s" % filter_string)
SyntaxError: One of the FILTER lines is malformed: ##FILTER=<ID=LOWQUAL,Description="Set if not true: (%TYPE=\"snp\" && %QUAL>=30) || (%TYPE=\"indel\" && %QUAL>=60)">

How can I solve it?

Thanks,

Miguel

**Comment by cbare** [comment]
Hi Miguel,

Sorry, I didn't see this for quite a while. I'm no longer maintaining this code. Perhaps, have a look at [mskcc's vcf2maf](https://github.com/mskcc/vcf2maf)?
